// Mocks generated by Mockito 5.4.6 from annotations
// in document_scanner/test/document_scanner_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i3;
import 'dart:typed_data' as _i9;
import 'dart:ui' as _i14;

import 'package:document_scanner/src/models/scan_result.dart' as _i4;
import 'package:document_scanner/src/models/scanned_document.dart' as _i7;
import 'package:document_scanner/src/services/camera_service.dart' as _i2;
import 'package:document_scanner/src/services/image_processor.dart' as _i13;
import 'package:document_scanner/src/services/pdf_generator.dart' as _i10;
import 'package:document_scanner/src/services/qr_scanner_service.dart' as _i11;
import 'package:document_scanner/src/services/storage_helper.dart' as _i6;
import 'package:flutter/material.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCaptureResult_0 extends _i1.SmartFake implements _i2.CaptureResult {
  _FakeCaptureResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_1 extends _i1.SmartFake implements _i3.Directory {
  _FakeDirectory_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQRScanResult_2 extends _i1.SmartFake implements _i4.QRScanResult {
  _FakeQRScanResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CameraService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraService extends _i1.Mock implements _i2.CameraService {
  MockCameraService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> hasCameraPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasCameraPermission, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasStoragePermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasStoragePermission, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestCameraPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestCameraPermission, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestStoragePermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestStoragePermission, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.CaptureResult> captureFromCamera({int? imageQuality = 95}) =>
      (super.noSuchMethod(
            Invocation.method(#captureFromCamera, [], {
              #imageQuality: imageQuality,
            }),
            returnValue: _i5.Future<_i2.CaptureResult>.value(
              _FakeCaptureResult_0(
                this,
                Invocation.method(#captureFromCamera, [], {
                  #imageQuality: imageQuality,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.CaptureResult>);

  @override
  _i5.Future<_i2.CaptureResult> importFromGallery({int? imageQuality = 95}) =>
      (super.noSuchMethod(
            Invocation.method(#importFromGallery, [], {
              #imageQuality: imageQuality,
            }),
            returnValue: _i5.Future<_i2.CaptureResult>.value(
              _FakeCaptureResult_0(
                this,
                Invocation.method(#importFromGallery, [], {
                  #imageQuality: imageQuality,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.CaptureResult>);

  @override
  _i5.Future<bool> requestAllPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestAllPermissions, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [StorageHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageHelper extends _i1.Mock implements _i6.StorageHelper {
  MockStorageHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void configure(_i6.StorageConfig? config) => super.noSuchMethod(
    Invocation.method(#configure, [config]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.Directory> getExternalStorageDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#getExternalStorageDirectory, []),
            returnValue: _i5.Future<_i3.Directory>.value(
              _FakeDirectory_1(
                this,
                Invocation.method(#getExternalStorageDirectory, []),
              ),
            ),
          )
          as _i5.Future<_i3.Directory>);

  @override
  String generateFilename({
    required _i7.DocumentType? documentType,
    required DateTime? timestamp,
    String? customFilename,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateFilename, [], {
              #documentType: documentType,
              #timestamp: timestamp,
              #customFilename: customFilename,
              #metadata: metadata,
            }),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#generateFilename, [], {
                #documentType: documentType,
                #timestamp: timestamp,
                #customFilename: customFilename,
                #metadata: metadata,
              }),
            ),
          )
          as String);

  @override
  _i5.Future<String> saveImageFile({
    required _i3.Directory? directory,
    required String? filename,
    required _i9.Uint8List? imageData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveImageFile, [], {
              #directory: directory,
              #filename: filename,
              #imageData: imageData,
            }),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#saveImageFile, [], {
                  #directory: directory,
                  #filename: filename,
                  #imageData: imageData,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> savePdfFile({
    required _i3.Directory? directory,
    required String? filename,
    required _i9.Uint8List? pdfData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savePdfFile, [], {
              #directory: directory,
              #filename: filename,
              #pdfData: pdfData,
            }),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#savePdfFile, [], {
                  #directory: directory,
                  #filename: filename,
                  #pdfData: pdfData,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<Map<String, String>> saveFiles({
    required _i3.Directory? directory,
    required String? filename,
    _i9.Uint8List? imageData,
    _i9.Uint8List? pdfData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveFiles, [], {
              #directory: directory,
              #filename: filename,
              #imageData: imageData,
              #pdfData: pdfData,
            }),
            returnValue: _i5.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i5.Future<Map<String, String>>);
}

/// A class which mocks [PdfGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfGenerator extends _i1.Mock implements _i10.PdfGenerator {
  MockPdfGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i9.Uint8List> generatePdf({
    required _i9.Uint8List? imageData,
    required _i7.DocumentType? documentType,
    required _i7.PdfResolution? resolution,
    _i7.DocumentFormat? documentFormat,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generatePdf, [], {
              #imageData: imageData,
              #documentType: documentType,
              #resolution: resolution,
              #documentFormat: documentFormat,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i5.Future<_i9.Uint8List>);

  @override
  _i5.Future<_i9.Uint8List> generateMultiPagePdf({
    required List<_i9.Uint8List>? imageDataList,
    required _i7.DocumentType? documentType,
    required _i7.PdfResolution? resolution,
    _i7.DocumentFormat? documentFormat,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateMultiPagePdf, [], {
              #imageDataList: imageDataList,
              #documentType: documentType,
              #resolution: resolution,
              #documentFormat: documentFormat,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i5.Future<_i9.Uint8List>);

  @override
  _i5.Future<_i9.Uint8List> generateReceiptPdf({
    required _i9.Uint8List? imageData,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateReceiptPdf, [], {
              #imageData: imageData,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i5.Future<_i9.Uint8List>);

  @override
  _i5.Future<_i9.Uint8List> generateManualPdf({
    required _i9.Uint8List? imageData,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateManualPdf, [], {
              #imageData: imageData,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i5.Future<_i9.Uint8List>);
}

/// A class which mocks [QRScannerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQRScannerService extends _i1.Mock implements _i11.QRScannerService {
  MockQRScannerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.QRScanResult> scanQRCode() =>
      (super.noSuchMethod(
            Invocation.method(#scanQRCode, []),
            returnValue: _i5.Future<_i4.QRScanResult>.value(
              _FakeQRScanResult_2(this, Invocation.method(#scanQRCode, [])),
            ),
          )
          as _i5.Future<_i4.QRScanResult>);

  @override
  _i5.Future<_i4.QRScanResult> scanQRCodeWithUI(_i12.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#scanQRCodeWithUI, [context]),
            returnValue: _i5.Future<_i4.QRScanResult>.value(
              _FakeQRScanResult_2(
                this,
                Invocation.method(#scanQRCodeWithUI, [context]),
              ),
            ),
          )
          as _i5.Future<_i4.QRScanResult>);

  @override
  _i4.QRScanResult processQRData(String? qrData) =>
      (super.noSuchMethod(
            Invocation.method(#processQRData, [qrData]),
            returnValue: _FakeQRScanResult_2(
              this,
              Invocation.method(#processQRData, [qrData]),
            ),
          )
          as _i4.QRScanResult);

  @override
  _i5.Future<_i7.ScannedDocument?> downloadManualFromUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#downloadManualFromUrl, [url]),
            returnValue: _i5.Future<_i7.ScannedDocument?>.value(),
          )
          as _i5.Future<_i7.ScannedDocument?>);

  @override
  _i5.Future<bool> validateManualUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#validateManualUrl, [url]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> getManualMetadata(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getManualMetadata, [url]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ImageProcessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageProcessor extends _i1.Mock implements _i13.ImageProcessor {
  MockImageProcessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i9.Uint8List> processImage(
    _i9.Uint8List? imageData,
    _i7.DocumentProcessingOptions? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processImage, [imageData, options]),
            returnValue: _i5.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i5.Future<_i9.Uint8List>);

  @override
  _i5.Future<_i9.Uint8List> applyImageEditing(
    _i9.Uint8List? imageData,
    _i7.ImageEditingOptions? editingOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyImageEditing, [imageData, editingOptions]),
            returnValue: _i5.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i5.Future<_i9.Uint8List>);

  @override
  _i5.Future<List<_i14.Offset>> detectDocumentEdges(_i9.Uint8List? imageData) =>
      (super.noSuchMethod(
            Invocation.method(#detectDocumentEdges, [imageData]),
            returnValue: _i5.Future<List<_i14.Offset>>.value(<_i14.Offset>[]),
          )
          as _i5.Future<List<_i14.Offset>>);

  @override
  Map<String, dynamic> analyzeImageQuality(_i9.Uint8List? imageData) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeImageQuality, [imageData]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
