// Mocks generated by Mockito 5.4.6 from annotations
// in document_scanner/test/ui/image_editing_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;
import 'dart:ui' as _i6;

import 'package:document_scanner/src/models/scanned_document.dart' as _i5;
import 'package:document_scanner/src/services/image_processor.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ImageProcessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageProcessor extends _i1.Mock implements _i2.ImageProcessor {
  MockImageProcessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Uint8List> processImage(
    _i4.Uint8List? imageData,
    _i5.DocumentProcessingOptions? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processImage, [imageData, options]),
            returnValue: _i3.Future<_i4.Uint8List>.value(_i4.Uint8List(0)),
          )
          as _i3.Future<_i4.Uint8List>);

  @override
  _i3.Future<_i4.Uint8List> applyImageEditing(
    _i4.Uint8List? imageData,
    _i5.ImageEditingOptions? editingOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyImageEditing, [imageData, editingOptions]),
            returnValue: _i3.Future<_i4.Uint8List>.value(_i4.Uint8List(0)),
          )
          as _i3.Future<_i4.Uint8List>);

  @override
  _i3.Future<List<_i6.Offset>> detectDocumentEdges(_i4.Uint8List? imageData) =>
      (super.noSuchMethod(
            Invocation.method(#detectDocumentEdges, [imageData]),
            returnValue: _i3.Future<List<_i6.Offset>>.value(<_i6.Offset>[]),
          )
          as _i3.Future<List<_i6.Offset>>);

  @override
  Map<String, dynamic> analyzeImageQuality(_i4.Uint8List? imageData) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeImageQuality, [imageData]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
