// Mocks generated by Mockito 5.4.6 from annotations
// in document_scanner/test/ui/multi_page_scanner_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i7;

import 'package:document_scanner/src/models/scan_result.dart' as _i2;
import 'package:document_scanner/src/models/scanned_document.dart' as _i5;
import 'package:document_scanner/src/services/document_scanner_service.dart'
    as _i3;
import 'package:document_scanner/src/services/pdf_generator.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeScanResult_0 extends _i1.SmartFake implements _i2.ScanResult {
  _FakeScanResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQRScanResult_1 extends _i1.SmartFake implements _i2.QRScanResult {
  _FakeQRScanResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DocumentScannerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentScannerService extends _i1.Mock
    implements _i3.DocumentScannerService {
  MockDocumentScannerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void configureStorage({
    String? customStorageDirectory,
    String? appName,
    String? pdfBrandingText,
  }) => super.noSuchMethod(
    Invocation.method(#configureStorage, [], {
      #customStorageDirectory: customStorageDirectory,
      #appName: appName,
      #pdfBrandingText: pdfBrandingText,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.ScanResult> scanDocument({
    required _i5.DocumentType? documentType,
    _i5.DocumentProcessingOptions? processingOptions,
    String? customFilename,
    bool? autoProcess = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scanDocument, [], {
              #documentType: documentType,
              #processingOptions: processingOptions,
              #customFilename: customFilename,
              #autoProcess: autoProcess,
            }),
            returnValue: _i4.Future<_i2.ScanResult>.value(
              _FakeScanResult_0(
                this,
                Invocation.method(#scanDocument, [], {
                  #documentType: documentType,
                  #processingOptions: processingOptions,
                  #customFilename: customFilename,
                  #autoProcess: autoProcess,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ScanResult>);

  @override
  _i4.Future<_i2.ScanResult> importDocument({
    required _i5.DocumentType? documentType,
    _i5.DocumentProcessingOptions? processingOptions,
    String? customFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importDocument, [], {
              #documentType: documentType,
              #processingOptions: processingOptions,
              #customFilename: customFilename,
            }),
            returnValue: _i4.Future<_i2.ScanResult>.value(
              _FakeScanResult_0(
                this,
                Invocation.method(#importDocument, [], {
                  #documentType: documentType,
                  #processingOptions: processingOptions,
                  #customFilename: customFilename,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ScanResult>);

  @override
  _i4.Future<_i2.ScanResult> scanDocumentWithProcessing({
    required _i5.DocumentType? documentType,
    _i5.DocumentProcessingOptions? processingOptions,
    String? customFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scanDocumentWithProcessing, [], {
              #documentType: documentType,
              #processingOptions: processingOptions,
              #customFilename: customFilename,
            }),
            returnValue: _i4.Future<_i2.ScanResult>.value(
              _FakeScanResult_0(
                this,
                Invocation.method(#scanDocumentWithProcessing, [], {
                  #documentType: documentType,
                  #processingOptions: processingOptions,
                  #customFilename: customFilename,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ScanResult>);

  @override
  _i4.Future<_i2.ScanResult> importDocumentWithProcessing({
    required _i5.DocumentType? documentType,
    _i5.DocumentProcessingOptions? processingOptions,
    String? customFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importDocumentWithProcessing, [], {
              #documentType: documentType,
              #processingOptions: processingOptions,
              #customFilename: customFilename,
            }),
            returnValue: _i4.Future<_i2.ScanResult>.value(
              _FakeScanResult_0(
                this,
                Invocation.method(#importDocumentWithProcessing, [], {
                  #documentType: documentType,
                  #processingOptions: processingOptions,
                  #customFilename: customFilename,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ScanResult>);

  @override
  _i4.Future<_i2.QRScanResult> scanQRCode() =>
      (super.noSuchMethod(
            Invocation.method(#scanQRCode, []),
            returnValue: _i4.Future<_i2.QRScanResult>.value(
              _FakeQRScanResult_1(this, Invocation.method(#scanQRCode, [])),
            ),
          )
          as _i4.Future<_i2.QRScanResult>);

  @override
  _i4.Future<_i2.ScanResult> scanQRCodeAndDownload({String? customFilename}) =>
      (super.noSuchMethod(
            Invocation.method(#scanQRCodeAndDownload, [], {
              #customFilename: customFilename,
            }),
            returnValue: _i4.Future<_i2.ScanResult>.value(
              _FakeScanResult_0(
                this,
                Invocation.method(#scanQRCodeAndDownload, [], {
                  #customFilename: customFilename,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ScanResult>);

  @override
  _i4.Future<_i2.ScanResult> downloadManualFromUrl({
    required String? url,
    String? customFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadManualFromUrl, [], {
              #url: url,
              #customFilename: customFilename,
            }),
            returnValue: _i4.Future<_i2.ScanResult>.value(
              _FakeScanResult_0(
                this,
                Invocation.method(#downloadManualFromUrl, [], {
                  #url: url,
                  #customFilename: customFilename,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ScanResult>);

  @override
  _i4.Future<_i2.ScanResult> finalizeScanResult(
    _i5.ScannedDocument? document,
    String? customFilename,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeScanResult, [document, customFilename]),
            returnValue: _i4.Future<_i2.ScanResult>.value(
              _FakeScanResult_0(
                this,
                Invocation.method(#finalizeScanResult, [
                  document,
                  customFilename,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.ScanResult>);

  @override
  _i4.Future<_i2.ScanResult> finalizeMultiPageSession(
    _i5.MultiPageScanSession? session, {
    String? customFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #finalizeMultiPageSession,
              [session],
              {#customFilename: customFilename},
            ),
            returnValue: _i4.Future<_i2.ScanResult>.value(
              _FakeScanResult_0(
                this,
                Invocation.method(
                  #finalizeMultiPageSession,
                  [session],
                  {#customFilename: customFilename},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ScanResult>);
}

/// A class which mocks [PdfGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfGenerator extends _i1.Mock implements _i6.PdfGenerator {
  MockPdfGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i7.Uint8List> generatePdf({
    required _i7.Uint8List? imageData,
    required _i5.DocumentType? documentType,
    required _i5.PdfResolution? resolution,
    _i5.DocumentFormat? documentFormat,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generatePdf, [], {
              #imageData: imageData,
              #documentType: documentType,
              #resolution: resolution,
              #documentFormat: documentFormat,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
          )
          as _i4.Future<_i7.Uint8List>);

  @override
  _i4.Future<_i7.Uint8List> generateMultiPagePdf({
    required List<_i7.Uint8List>? imageDataList,
    required _i5.DocumentType? documentType,
    required _i5.PdfResolution? resolution,
    _i5.DocumentFormat? documentFormat,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateMultiPagePdf, [], {
              #imageDataList: imageDataList,
              #documentType: documentType,
              #resolution: resolution,
              #documentFormat: documentFormat,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
          )
          as _i4.Future<_i7.Uint8List>);

  @override
  _i4.Future<_i7.Uint8List> generateReceiptPdf({
    required _i7.Uint8List? imageData,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateReceiptPdf, [], {
              #imageData: imageData,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
          )
          as _i4.Future<_i7.Uint8List>);

  @override
  _i4.Future<_i7.Uint8List> generateManualPdf({
    required _i7.Uint8List? imageData,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateManualPdf, [], {
              #imageData: imageData,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
          )
          as _i4.Future<_i7.Uint8List>);
}
